const heroes = [
    { name: "Anti-Mage",            roles: ["Керри"],                              attribute: "Ловкость",    strength: 21, agility: 24, intelligence: 15, combat: "Ближний бой"  },
    { name: "Legion Commander",     roles: ["Керри", "Инициатор"],                 attribute: "Сила",        strength: 25, agility: 18, intelligence: 20, combat: "Ближний бой"  },
    { name: "Lion",                 roles: ["Саппорт", "Контролер", "Нукер"],      attribute: "Интеллект",   strength: 18, agility: 15, intelligence: 22, combat: "Дальний бой" },
    { name: "Crystal Maiden",       roles: ["Саппорт", "Контролер", "Нукер"],      attribute: "Интеллект",   strength: 19, agility: 16, intelligence: 21, combat: "Дальний бой" },
    { name: "Invoker",              roles: ["Керри", "Нукер", "Контролер"],        attribute: "Интеллект",   strength: 19, agility: 14, intelligence: 22, combat: "Дальний бой" },
    { name: "Earthshaker",          roles: ["Саппорт", "Инициатор", "Контролер"],  attribute: "Сила",        strength: 22, agility: 12, intelligence: 18, combat: "Ближний бой"  },
    { name: "Juggernaut",           roles: ["Керри"],                              attribute: "Ловкость",    strength: 20, agility: 26, intelligence: 14, combat: "Ближний бой"  },
    { name: "Pudge",                roles: ["Контролер", "Инициатор", "Танк"],     attribute: "Сила",        strength: 25, agility: 14, intelligence: 16, combat: "Ближний бой"  },
    { name: "Shadow Fiend",         roles: ["Керри", "Нукер"],                     attribute: "Ловкость",    strength: 19, agility: 20, intelligence: 18, combat: "Дальний бой" },
    { name: "Storm Spirit",         roles: ["Керри", "Нукер"],                     attribute: "Интеллект",   strength: 21, agility: 22, intelligence: 23, combat: "Ближний бой"  },
    { name: "Phantom Assassin",     roles: ["Керри"],                              attribute: "Ловкость",    strength: 19, agility: 23, intelligence: 15, combat: "Ближний бой"  },
    { name: "Riki",                 roles: ["Керри"],                              attribute: "Ловкость",    strength: 18, agility: 23, intelligence: 14, combat: "Ближний бой"  },
    { name: "Sniper",               roles: ["Керри", "Нукер"],                     attribute: "Ловкость",    strength: 19, agility: 27, intelligence: 15, combat: "Дальний бой" },
    { name: "Templar Assassin",     roles: ["Керри", "Нукер"],                     attribute: "Ловкость",    strength: 21, agility: 23, intelligence: 16, combat: "Ближний бой"  },
    { name: "Ursa",                 roles: ["Керри", "Танк"],                      attribute: "Ловкость",    strength: 24, agility: 18, intelligence: 16, combat: "Ближний бой"  },
    { name: "Lina",                 roles: ["Керри", "Саппорт", "Нукер"],          attribute: "Интеллект",   strength: 20, agility: 23, intelligence: 30, combat: "Дальний бой" },
    { name: "Windranger",           roles: ["Керри", "Саппорт", "Нукер"],          attribute: "Интеллект",   strength: 18, agility: 17, intelligence: 22, combat: "Дальний бой" },
    { name: "Zeus",                 roles: ["Нукер"],                              attribute: "Интеллект",   strength: 19, agility: 11, intelligence: 22, combat: "Дальний бой" },
    { name: "Slark",                roles: ["Керри"],                              attribute: "Ловкость",    strength: 21, agility: 21, intelligence: 16, combat: "Ближний бой"  },
    { name: "Faceless Void",        roles: ["Керри", "Контролер"],                 attribute: "Ловкость",    strength: 20, agility: 19, intelligence: 15, combat: "Ближний бой"  },
    { name: "Queen of Pain",        roles: ["Керри", "Нукер"],                     attribute: "Интеллект",   strength: 18, agility: 22, intelligence: 25, combat: "Ближний бой"  },
    { name: "Wraith King",          roles: ["Керри", "Саппорт", "Танк"],           attribute: "Сила",        strength: 22, agility: 16, intelligence: 18, combat: "Ближний бой"  },
    { name: "Drow Ranger",          roles: ["Керри"],                              attribute: "Ловкость",    strength: 16, agility: 21, intelligence: 15, combat: "Дальний бой" },
    { name: "Mirana",               roles: ["Керри", "Саппорт"],                   attribute: "Ловкость",    strength: 18, agility: 24, intelligence: 22, combat: "Дальний бой" },
    { name: "Nyx Assassin",         roles: ["Контролер", "Нукер", "Инициатор"],    attribute: "Ловкость",    strength: 17, agility: 21, intelligence: 21, combat: "Ближний бой"  },
    { name: "Bounty Hunter",        roles: ["Нукер"],                              attribute: "Ловкость",    strength: 20, agility: 21, intelligence: 22, combat: "Ближний бой"  },
    { name: "Clockwerk",            roles: ["Инициатор", "Контролер", "Танк"],     attribute: "Сила",        strength: 26, agility: 13, intelligence: 18, combat: "Ближний бой"  },
    { name: "Omniknight",           roles: ["Саппорт", "Танк"],                    attribute: "Сила",        strength: 23, agility: 15, intelligence: 16, combat: "Ближний бой"  },
    { name: "Enigma",               roles: ["Контролер", "Инициатор"],             attribute: "Интеллект",   strength: 21, agility: 14, intelligence: 19, combat: "Дальний бой" },
    { name: "Tinker",               roles: ["Керри", "Нукер"],                     attribute: "Интеллект",   strength: 19, agility: 13, intelligence: 30, combat: "Дальний бой" },
    { name: "Nature's Prophet",     roles: ["Керри"],                              attribute: "Интеллект",   strength: 21, agility: 22, intelligence: 23, combat: "Дальний бой" },
    { name: "Dark Seer",            roles: ["Инициатор"],                          attribute: "Интеллект",   strength: 22, agility: 12, intelligence: 21, combat: "Ближний бой"  },
    { name: "Axe",                  roles: ["Инициатор", "Танк", "Контролер"],     attribute: "Сила",        strength: 25, agility: 20, intelligence: 18, combat: "Ближний бой"  },
    { name: "Bristleback",          roles: ["Керри", "Танк", "Инициатор"],         attribute: "Сила",        strength: 22, agility: 17, intelligence: 14, combat: "Ближний бой"  },
    { name: "Centaur Warrunner",    roles: ["Инициатор", "Танк", "Контролер"],     attribute: "Сила",        strength: 27, agility: 15, intelligence: 15, combat: "Ближний бой"  },
    { name: "Timbersaw",            roles: ["Танк", "Нукер"],                      attribute: "Сила",        strength: 25, agility: 16, intelligence: 19, combat: "Ближний бой"  },
    { name: "Sand King",            roles: ["Инициатор", "Контролер", "Саппорт"],  attribute: "Сила",        strength: 22, agility: 19, intelligence: 19, combat: "Ближний бой"  },
    { name: "Tidehunter",           roles: ["Инициатор", "Танк", "Контролер"],     attribute: "Сила",        strength: 27, agility: 15, intelligence: 18, combat: "Ближний бой"  },
    { name: "Slardar",              roles: ["Керри", "Танк", "Инициатор"],         attribute: "Сила",        strength: 21, agility: 17, intelligence: 15, combat: "Ближний бой"  },
    { name: "Spirit Breaker",       roles: ["Инициатор", "Контролер", "Танк"],     attribute: "Сила",        strength: 28, agility: 17, intelligence: 14, combat: "Ближний бой"  },
    { name: "Lycan",                roles: ["Керри"],                              attribute: "Сила",        strength: 26, agility: 16, intelligence: 23, combat: "Ближний бой"  },
    { name: "Chaos Knight",         roles: ["Керри", "Контролер", "Танк"],         attribute: "Сила",        strength: 22, agility: 18, intelligence: 18, combat: "Ближний бой"  },
    { name: "Kunkka",               roles: ["Керри", "Саппорт", "Контролер"],      attribute: "Сила",        strength: 24, agility: 14, intelligence: 18, combat: "Ближний бой"  },
    { name: "Dazzle",               roles: ["Саппорт", "Нукер"],                   attribute: "Интеллект",   strength: 18, agility: 20, intelligence: 25, combat: "Дальний бой" },
    { name: "Witch Doctor",         roles: ["Саппорт", "Нукер", "Контролер"],      attribute: "Интеллект",   strength: 18, agility: 13, intelligence: 22, combat: "Дальний бой" },
    { name: "Lich",                 roles: ["Саппорт", "Нукер"],                   attribute: "Интеллект",   strength: 20, agility: 15, intelligence: 24, combat: "Дальний бой" },
    { name: "Ancient Apparition",   roles: ["Саппорт", "Контролер", "Нукер"],      attribute: "Интеллект",   strength: 20, agility: 15, intelligence: 25, combat: "Дальний бой" },
    { name: "Shadow Shaman",        roles: ["Саппорт", "Контролер"],               attribute: "Интеллект",   strength: 23, agility: 16, intelligence: 25, combat: "Дальний бой" },
    { name: "Ogre Magi",            roles: ["Саппорт", "Танк", "Нукер"],           attribute: "Интеллект",   strength: 23, agility: 14, intelligence: 15, combat: "Ближний бой"  },
    { name: "Rubick",               roles: ["Саппорт", "Контролер"],               attribute: "Интеллект",   strength: 21, agility: 23, intelligence: 28, combat: "Дальний бой" },
    { name: "Disruptor",            roles: ["Саппорт", "Контролер", "Нукер"],      attribute: "Интеллект",   strength: 21, agility: 15, intelligence: 20, combat: "Дальний бой" },
    { name: "Jakiro",               roles: ["Саппорт", "Нукер"],                   attribute: "Интеллект",   strength: 25, agility: 10, intelligence: 28, combat: "Дальний бой" },
    { name: "Silencer",             roles: ["Керри", "Саппорт", "Контролер"],      attribute: "Интеллект",   strength: 19, agility: 22, intelligence: 25, combat: "Дальний бой" },
    { name: "Necrophos",            roles: ["Керри", "Нукер", "Танк"],             attribute: "Интеллект",   strength: 18, agility: 12, intelligence: 21, combat: "Дальний бой" },
    { name: "Death Prophet",        roles: ["Керри", "Нукер"],                     attribute: "Интеллект",   strength: 21, agility: 14, intelligence: 24, combat: "Дальний бой" }
];


export default heroes;
